accounts/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('archive/<str:month>/<int:year>/', blog_view, name='archive'),
]

restaurant/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from menu.sitemaps import MenuSitemap
from reservation.sitemaps import ReservationSitemap
from restaurant.setting.dev import STATIC_ROOT, MEDIA_ROOT

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'menu': MenuSitemap,
    'reservation': ReservationSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('menu/', include('menu.urls')),
    path('reservation/', include('reservation.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField


class CustomUser(AbstractUser):
    email = models.EmailField(_('email address'), unique=True, error_messages={'unique': (
        "A user with that email already exists.")})

    phone = PhoneNumberField(null=True, blank=True, unique=True, error_messages={'unique': (
        "A user with that phone number already exists.")})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django import forms


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'phone', 'first_name', 'last_name', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Email / Username')
    remember_me = forms.BooleanField(required=False)

accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.forms import LoginForm, RegisterForm
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


# Create your views here.
def login_view(request):
    next = ''
    if request.GET:
        if 'next' in request.GET:
            next = request.GET['next']

    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            remember_me = form.cleaned_data['remember_me']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                if not remember_me:
                    request.session.set_expiry(0)
            else:
                messages.add_message(request, messages.ERROR, 'Username or Password is not correct. Try again ...')
        else:
            messages.add_message(request, messages.ERROR, 'Username or Password is not correct. Try again ...')
        if next != "":
            return HttpResponseRedirect(next)
    return render(request, 'accounts/login.html')


@login_required
def logout_view(request):
    logout(request)
    return redirect('accounts:login')


def signup_view(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'You have successfully registered.')
                return redirect('accounts:login')

            else:
                if form.errors:
                    for field in form:
                        for error in field.errors:
                            messages.add_message(request, messages.ERROR, error)

        return render(request, 'accounts/signup.html')
    else:
        messages.add_message(request, messages.ERROR, "If you want to sign up, you must sign out first.")
        return redirect('accounts:login')


##########################  Reset Password  ###############################
class CustomPasswordResetView(PasswordResetView):
    from_email = 'IT@mahyarnazari.ir'
    template_name = 'accounts/resetpassword/password_reset.html'
    email_template_name = 'accounts/resetpassword/password_reset_email.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = 'accounts/resetpassword/password_reset_done.html'


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'accounts/resetpassword/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'accounts/resetpassword/password_reset_complete.html'

templates/accounts/account_base.html
{% extends 'base.html' %}
{% load static %}
{% load background_tags %}
{% load compress %}
{% block content %}

    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/style.css' %}">
    {% endcompress %}

    {% background as background %}

    <section class="bg-title-page flex-c-m p-t-160 p-b-80 p-l-15 p-r-15 ftco-section"
             style="background-image: url({{ background|image_url:'account' }});">

        {% block content_login %}

        {% endblock %}
    </section>
{% endblock %}

templates/accounts/login.html
{% extends 'accounts/account_base.html' %}
{% block content_login %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="login-wrap py-5">
                    {% if request.user.is_authenticated %}
                        <h3 class="mb-4 text-center">{{ request.user.get_full_name }}, you are already logged
                            in.</h3>
                    {% else %}
                        <h3 class="mb-4 text-center">Have an account?</h3>
                        <form method="Post" class="signin-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="username" class="form-control"
                                       placeholder="Username / Email"
                                       required>
                            </div>
                            <div class="form-group">
                                <input name="password" type="password" class="form-control" placeholder="Password"
                                       required>
                                <span toggle="password"
                                      class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control btn btn-primary submit px-3">Sign In
                                </button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">Remember Me
                                        <input type="checkbox" checked name="remember_me">
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="{% url 'accounts:password-reset' %}" style="color: #fff">Forgot
                                        Password</a>
                                </div>
                            </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'accounts/account_base.html' %}
{% block content_login %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
                <div class="login-wrap py-5">
                    <h3 class="mb-4 text-center">Create a new account</h3>
                    <form method="Post" action="{% url 'accounts:signup' %}" class="signin-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <input type="text" name="username" class="form-control" placeholder="Username"
                                   required autocomplete="on">
                        </div>
                        <div class="form-group">
                            <input type="text" name="first_name" class="form-control" placeholder="Firstname"
                                   required autocomplete="on">
                        </div>
                        <div class="form-group">
                            <input type="text" name="last_name" class="form-control" placeholder="Lastname"
                                   required autocomplete="on">
                        </div>
                        <div class="form-group">
                            <input type="text" name="email" class="form-control" placeholder="Email"
                                   required autocomplete="on">
                        </div>
                        <div class="form-group">
                            <input type="text" name="phone" class="form-control" placeholder="Phone (+98xxxxxxxxxx)"
                                   required autocomplete="on">
                        </div>
                        <div class="form-group">
                            <input name="password1" type="password" class="form-control" placeholder="Password"
                                   required>
                            {#                                <span toggle="#password-field"#}
                            {#                                      class="fa fa-fw fa-eye field-icon toggle-password"></span>#}
                        </div>
                        <div class="form-group">
                            <input name="password2" type="password" class="form-control"
                                   placeholder="Confirm Password"
                                   required>
                            {#                                <span toggle="#password-field"#}
                            {#                                      class="fa fa-fw fa-eye field-icon toggle-password"></span>#}
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control btn btn-primary submit px-3">Sign UP
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}