blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('archive/<str:month>/<int:year>/', blog_view, name='archive'),
]

main/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main.views import *


app_name = 'website'
urlpatterns = [
    path('', index_view, name='index'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('newsletter/', newsletter_view, name='newsletter'),
    path('maintenance/', maintenance_view, name='maintenance'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

menu/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from menu.views import *
from menu.feeds import MenuFeed

app_name = 'menu'
urlpatterns = [
    path('', menu_view, name='menu'),
    path('rss/feed/', MenuFeed()),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from menu.sitemaps import MenuSitemap
from reservation.sitemaps import ReservationSitemap
from restaurant.setting.dev import STATIC_ROOT, MEDIA_ROOT

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'menu': MenuSitemap,
    'reservation': ReservationSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('menu/', include('menu.urls')),
    path('reservation/', include('reservation.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

main/models.py
from django.db import models
from accounts.models import CustomUser
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill  # or try ResizeToFill
from osm_field.fields import LatitudeField, LongitudeField, OSMField


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    phone = models.IntegerField(blank=True, null=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name


class Newsletter(models.Model):
    email = models.EmailField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.email


class Addresses(models.Model):
    title = models.CharField(max_length=50, null=True)
    location = models.CharField(max_length=255)
    phone = models.CharField(max_length=20)
    work_start_time = models.TimeField()
    work_end_time = models.TimeField()
    iframe_url = models.URLField(null=True, blank=True, max_length=500)
    latitude = LatitudeField(null=True, blank=True)
    longitude = LongitudeField(null=True, blank=True)

    class Meta:
        ordering = ['-title']

    def __str__(self):
        return self.title


class About(models.Model):
    image = ProcessedImageField(upload_to='about/', format='JPEG', processors=[ResizeToFill(393, 393)],
                                options={'quality': 80}, default='default/no-image.jpg')
    TYPE_CHOICES = [('Summary', 'Summary'), ('Feature', 'Feature')]
    type = models.CharField(choices=TYPE_CHOICES, default='Feature', max_length=10)
    title = models.CharField(max_length=40, null=True, blank=True)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['type', '-title']

    def __str__(self):
        return self.title


class Chef(models.Model):
    image = ProcessedImageField(upload_to='about/', format='JPEG', processors=[ResizeToFill(320, 320)],
                                options={'quality': 80}, default='default/no-avatar.jpg')

    name = models.CharField(max_length=25)
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-name']

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from main.models import Contact, Newsletter


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = '__all__'

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from restaurant.setting.prod import SET_ENDTIME
from main.models import Addresses, Chef, About
from main.forms import ContactForm, NewsletterForm
from django.contrib import messages
from datetime import datetime


# Create your views here.
def index_view(request):
    return render(request, 'main/index.html')


def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            changed_form = form.save(commit=False)
            changed_form.name = 'Unknown'
            changed_form.save()
            messages.add_message(request, messages.SUCCESS,
                                 '{} ,your ticket has been submitted successfully.'.format(request.POST['name']))
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.add_message(request, messages.ERROR, error)

    form = ContactForm()
    addresses = Addresses.objects.all()
    return render(request, 'main/contact.html', {'form': form, 'addresses': addresses})


def about_view(request):
    chefs = Chef.objects.all()
    about = About.objects.all()
    features = about.filter(type='Feature').order_by('-updated_date')
    summary = about.filter(type='Summary').order_by('-updated_date').first()
    context = {'chefs': chefs, 'features': features, 'summary': summary}
    return render(request, 'main/about.html', context=context)


def newsletter_view(request):
    if request.method == 'POST':
        form = NewsletterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Your email address has been saved successfully.')
        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.add_message(request, messages.ERROR, error)
    return HttpResponseRedirect('/')


def maintenance_view(request):
    datetime_object = datetime.strptime(SET_ENDTIME, '%Y/%m/%d %H:%M:%S')
    duration = datetime_object - datetime.now()
    duration_in_s = duration.total_seconds()
    hours = int(divmod(duration_in_s, 3600)[0])
    if hours < 0:
        hours = 24
    return render(request, 'maintenance/maintenance.html', {'hours': hours})

templates/main/about.html
{% extends 'base.html' %}
{% load main_tags %}
{% load background_tags %}
{% block content %}
    {% background as background %}
    <!-- Title Page -->
    <section class="bg-title-page flex-c-m p-b-80 p-l-15 p-r-15"
             style="min-height: 100%; background-image: url({{ background|image_url:'about_top' }});">
        <h2 class="tit6 t-center">
            About Us
        </h2>
    </section>

    <!-- Our Story -->
    <section id='summary' class="bg2-pattern p-t-116 p-b-110 t-center p-l-15 p-r-15">
		<span class="tit2 t-center">
			{{ summary.title|split:1 }}
		</span>

        <h3 class="tit3 t-center m-b-35 m-t-5">
            {{ summary.title|split:2 }}
        </h3>
        <div class="col-8 t-center size32 m-l-r-auto">
            {{ summary.content|safe }}
        </div>
    </section>

    <!-- Banner 1 -->
    <div class="parallax0 parallax100" style="background-image: url({{ background|image_url:'about_middle' }});">
        <div class="overlay0-parallax t-center size33"></div>
    </div>

    <!-- Features -->
    <section id="feature" class="bg1-pattern p-t-120 p-b-105">
        <div class="container">
            {% for feature in features %}
                {% if forloop.counter|divisibleby:2 %}
                    <div id="feature/{{ feature.id }}" class="row p-t-50">
                        <div class="col-md-6 p-t-45 p-b-30">
                            <div class="wrap-text-delicious t-center">
						<span class="tit2 t-center">
							{{ feature.title|split:1 }}
						</span>
                                <h3 class="tit3 t-center m-b-35 m-t-5">
                                    {{ feature.title|split:2 }}
                                </h3>
                                <p class="t-center m-b-22 size3 m-l-r-auto">
                                    {{ feature.content|safe }}
                                </p>
                            </div>
                        </div>
                        <div class="col-md-6 p-b-30">
                            <div class="wrap-pic-delicious size2 bo-rad-10 hov-img-zoom m-l-r-auto">
                                <img src="{{ feature.image.url }}" alt="IMG-OUR">
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div id="feature/{{ feature.id }}" class="row p-t-50">
                        <div class="col-md-6 p-b-30">
                            <div class="wrap-pic-romantic size2 bo-rad-10 hov-img-zoom m-l-r-auto">
                                <img src="{{ feature.image.url }}" alt="IMG-OUR">
                            </div>
                        </div>
                        <div class="col-md-6 p-t-45 p-b-30">
                            <div class="wrap-text-romantic t-center">
						<span class="tit2 t-center">
							{{ feature.title|split:1 }}
						</span>
                                <h3 class="tit3 t-center m-b-35 m-t-5">
                                    {{ feature.title|split:2 }}
                                </h3>
                                <p class="t-center m-b-22 size3 m-l-r-auto">
                                    {{ feature.content|safe }}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </section>

    <!-- Banner 2-->
    <div class="parallax0 parallax100" style="background-image: url({{ background|image_url:'about_bottom' }});">
        <div class="overlay0-parallax t-center size33"></div>
    </div>

    <!-- Chef -->
    <section class="section-review bgwhite p-t-115 p-b-95">
        <div class=" container t-center">
			<span class="tit2 t-center">
				Meet Our
			</span>
            <h3 class="tit5 t-center m-b-50 m-t-5">
                Chef
            </h3>
            <div class="row ">
                <div class="wrap-slick3 slick3 col-lg-10 mx-auto">
                    {% for chef in chefs %}
                        <!-- -Block5 -->
                        <div class="blo5 pos-relative p-t-60 t-center item-slick3 wrap-content-slide3 p-b-50 p-t-50 mx-1">
                            <div class="pic-blo5 size14 bo4 wrap-cir-pic hov-img-zoom ab-c-t">
                                <a><img src="{{ chef.image.url }}" alt="IGM-AVATAR"></a>
                            </div>
                            <div class="text-blo5 size34 t-center bo-rad-10 bo7 p-t-90 p-l-35 p-r-35 p-b-30">
                                <span class="txt34 dis-block p-b-6">
                                    {{ chef.name }}
                                </span>

                                <span class="dis-block t-center txt35 p-b-25">
								{{ chef.title }}
							</span>
                                <p class="t-center">
                                    {{ chef.content|safe }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="wrap-slick3-dots m-t-30"></div>
    </section>
{% endblock %}

templates/main/contact.html
{% extends 'base.html' %}
{% load static %}
{% load background_tags %}
{% block content %}

    <!-- Title Page -->
    <section class="bg-title-page flex-c-m p-t-160 p-b-80 p-l-15 p-r-15"
             style="background-image: url({{ background|image_url:'contact' }});">
        <h2 class="tit6 t-center">
            Contact
        </h2>
    </section>

    <!-- Contact form -->
    <section class="section-contact bg1-pattern p-t-90 p-b-113">
        <!-- Map -->
        <div class="container">
            <div class="row mt-5">
                {% for address in addresses %}
                    <div class="col-md-6">
                        <div class="card d-flex h-100 mb-3 mb-md-0">
                            <div class="card-body d-flex flex-column">
                                <div class="mb-3 tit7">
                                    {{ address.title }}
                                </div>
                                <div style="height: 200px" class="mb-3">
                                    <div class="map-container" data-src="{{ address.iframe_url }}"
                                         style="background: url({% static 'main/images/map.webp' %}) no-repeat center;"></div>
                                </div>
                                <address class="d-flex align-items-center">
                                    <i class="fa fa-map-marker fs-24 mr-4"></i>
                                    <span class="txt10">Address: {{ address.location }}</span>
                                </address>
                                <div class="mb-3">
                                    <i class="fa fa-phone fs-24 mr-3"></i>
                                    <span class="txt10">
                                         Phone: {{ address.phone }}
                                    </span>
                                </div>
                                <div>

                                    <i class="fa fa-clock-o fs-24 mr-3"></i>
                                    <span class="txt10">
                                         Opening Hours: {{ address.work_start_time }} – {{ address.work_end_time }}
                                    </span>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="container">
            <h3 class="tit7 t-center p-b-62 p-t-105">
                Send us a Message
            </h3>
            <form class="wrap-form-reservation size22 m-l-r-auto" action="{% url 'website:contact' %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-4">
                        <!-- Name -->
                        <span class="txt9">
							Name
						</span>
                        <div class="wrap-inputname size12 bo2 bo-rad-10 m-t-3 m-b-23">
                            <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="name" placeholder="Name">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <!-- Email -->
                        <span class="txt9">
							Email
						</span>
                        <div class="wrap-inputemail size12 bo2 bo-rad-10 m-t-3 m-b-23">
                            <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="email" placeholder="Email">
                        </div>
                    </div>
                    <div class="col-md-4">
                        <!-- Phone -->
                        <span class="txt9">
							Phone
						</span>
                        <div class="wrap-inputphone size12 bo2 bo-rad-10 m-t-3 m-b-23">
                            <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="phone" placeholder="Phone">
                        </div>
                    </div>
                    <div class="col-12">
                        <!-- Message -->
                        <span class="txt9">
							Message
						</span>
                        <textarea class="bo-rad-10 size35 bo2 txt10 p-l-20 p-t-15 m-b-10 m-t-3" name="message"
                                  placeholder="Message"></textarea>
                    </div>
                </div>
                <div class="wrap-btn-booking flex-c-m m-t-13">
                    <!-- Button3 -->
                    <button type="submit" class="btn3 flex-c-m size36 txt11 trans-0-4">
                        Submit
                    </button>
                </div>
            </form>
        </div>
    </section>

    <script>
        window.addEventListener('load',
            function (e) {
                const mapContainers = document.getElementsByClassName('map-container');
                for (let i = 0; i < mapContainers.length; i++) {
                    const map = mapContainers[i];
                    var frame = document.createElement('iframe');
                    frame.src = map.getAttribute('data-src');
                    map.appendChild(frame);
                }
            });
    </script>
{% endblock %}

templates/main/index.html
{% extends 'base.html' %}
{% load background_tags %}
{% load main_tags %}
{% load blog_tags %}
{% load humanize %}
{% block content %}

    <section class="bg-title-page"
             style="background-image: url({{ background|image_url:'home_top' }});">
        <div class="flex-col-c-m p-l-15 p-r-15 p-t-150 p-b-150">
            <span class="txt1 t-center" data-appear="fadeInUp">
    							Welcome to
    						</span>

            <h1 class="tit37 t-center m-b-37 flex-row flex-column" data-appear="fadeInUp">
                Mahyar Restaurant
            </h1>

            <div data-appear="zoomIn">
                <!-- Button1 -->
                <a href="{% url 'menu:menu' %}" class="btn1 flex-c-m size1 txt3 trans-0-4">
                    Look Menu
                </a>
            </div>
        </div>
    </section>

    <!-- Summary -->
    {% about as about %}
    <section class="section-welcome bg2-pattern p-t-120 p-b-105">
        <div class="container">
            <div class="row">
                <div class="col-md-6 p-t-45 p-b-30">
                    <div class="wrap-text-welcome t-center">
						<span class="tit2 t-center">
							{{ about.summary.title }}
						</span>

                        <h3 class="tit3 t-center m-b-35 m-t-5">
                            Welcome
                        </h3>

                        <p class="t-center m-b-22 size3 m-l-r-auto">
                            {{ about.summary.content|striptags|safe|truncatechars:200 }}
                        </p>

                        <a href="{% url 'website:about' %}#summary" class="txt4">
                            Our Story
                            <i class="fa fa-long-arrow-right m-l-10" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>

                <div class="col-md-6 p-b-30">
                    <div class="wrap-pic-welcome size2 bo-rad-10 hov-img-zoom m-l-r-auto">
                        <img src="{{ about.summary.image.url }}" alt="IMG-OUR">
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Image Middle1 -->
    <div class="parallax0 parallax100" style="background-image: url({{ background|image_url:'home_middle_1' }});">
        <div class="overlay0-parallax t-center size33"></div>
    </div>

    <!-- Feature -->
    <section class="section-intro bg2-pattern">
        <div class="content-intro p-t-77 p-b-133">
            <div class="container">
                <div class="title-section-ourmenu t-center m-b-22">
				<span class="tit2 t-center">
					Discover
				</span>
                    <h2 class="tit5 t-center m-t-2">
                        Your Dreams
                    </h2>
                </div>
                <div class="row">
                    {% for feature in about.features %}
                        <div class="col-md-4 p-t-30">
                            <!-- Block1 -->
                            <div class="blo1">
                                <div class="wrap-pic-blo1 bo-rad-10 hov-img-zoom">
                                    <a href="{% url 'website:about' %}#feature/{{ feature.id }}"><img
                                            src="{{ feature.image.url }}" alt="IMG-INTRO"></a>
                                </div>
                                <div class="wrap-text-blo1 p-t-35">
                                    <a href="{% url 'website:about' %}#feature/{{ feature.id }}"><h4
                                            class="txt5 color0-hov trans-0-4 m-b-13">
                                        {{ feature.title }}
                                    </h4></a>
                                    <p class="m-b-20">
                                        {{ feature.content|striptags|safe|truncatewords:30 }}
                                    </p>
                                    <a href="{% url 'website:about' %}#feature/{{ feature.id }}" class="txt4">
                                        Learn More
                                        <i class="fa fa-long-arrow-right m-l-10" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <!-- Image Middle2 -->
    <div class="parallax0 parallax100" style="background-image: url({{ background|image_url:'home_middle_2' }});">
        <div class="overlay0-parallax t-center size33"></div>
    </div>

    <!-- Menu -->
    <section class="section-ourmenu bg2-pattern p-t-115 p-b-120">
        <div class="container">
            <div class="title-section-ourmenu t-center m-b-22">
				<span class="tit2 t-center">
					Discover
				</span>
                <h2 class="tit5 t-center m-t-2">
                    Our Menu
                </h2>
            </div>
            <div class="row">
                <div class="col-md-8">
                    <div class="row">
                        <div class="col-sm-6">
                            <!-- Breakfast -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_breakfast' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#breakfast" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Breakfast</h3>
                                </a>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <!-- Lunch -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_lunch' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#lunch" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Lunch</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-12">
                            <!-- Dinner -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_dinner' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#dinner" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Dinner</h3>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="row">
                        <div class="col-12">
                            <!-- Drink -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_drink' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#drink" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Drink</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-12">
                            <!-- Starter -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_starter' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#starter" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Starters</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-12">
                            <!-- Desert -->
                            <div class="item-ourmenu bo-rad-10 hov-img-zoom pos-relative m-t-30">
                                <img src="{{ background|image_thumbnail_url:'menu_dessert' }}" alt="IMG-MENU">

                                <!-- Button2 -->
                                <a href="{% url "menu:menu" %}#dessert" class="btn2 flex-c-m txt5 ab-c-m size5">
                                    <h3 class="txt5 t-center m-t-2">Dessert</h3>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Image Bottom -->
    <div class="parallax0 parallax100" style="background-image: url({{ background|image_url:'home_bottom' }});">
        <div class="overlay0-parallax t-center size33"></div>
    </div>

    <!-- Blog -->
    <section class="section-blog bg2-pattern p-t-115 p-b-123">
        <div class="container">
            <div class="title-section-ourmenu t-center m-b-22">
				<span class="tit2 t-center">
					Latest News
				</span>

                <h2 class="tit5 t-center m-t-2">
                    The Blog
                </h2>
            </div>
            <div class="row">
                {% latest_posts as posts %}
                {% for post in posts %}
                    <div class="col-md-4 p-t-30">
                        <!-- Block1 -->
                        <div class="blo1">
                            <div class="wrap-pic-blo1 bo-rad-10 hov-img-zoom pos-relative">
                                <a href="{% url 'blog:single' pid=post.id %}"><img src="{{ post.image.url }}"
                                                                                   alt="IMG-INTRO"></a>

                                <div class="time-blog">
                                    {{ post.created_date|naturaltime }}
                                </div>
                            </div>
                            <div class="wrap-text-blo1 p-t-35">
                                <a href="{% url 'blog:single' pid=post.id %}"><h4
                                        class="txt5 color0-hov trans-0-4 m-b-13">
                                    {{ post.title }}
                                </h4></a>
                                <p class="m-b-20">
                                    {{ post.content|striptags|safe|truncatewords:20 }}
                                </p>
                                <a href="{% url 'blog:single' pid=post.id %}" class="txt4">
                                    Continue Reading
                                    <i class="fa fa-long-arrow-right m-l-10" aria-hidden="true"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}