accounts/urls.py
from django.conf import settings
from django.urls import path
from django.conf.urls.static import static
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),
    path('password-reset/', CustomPasswordResetView.as_view(), name='password-reset'),
    path('password-reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('archive/<str:month>/<int:year>/', blog_view, name='archive'),
]

reservation/urls.py
from django.urls import path, include
from reservation.views import *


app_name = 'reservation'
urlpatterns = [
    path('', reservation_view, name='reservation'),

]

restaurant/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from menu.sitemaps import MenuSitemap
from reservation.sitemaps import ReservationSitemap
from restaurant.setting.dev import STATIC_ROOT, MEDIA_ROOT

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'menu': MenuSitemap,
    'reservation': ReservationSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('menu/', include('menu.urls')),
    path('reservation/', include('reservation.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

reservation/models.py
from django.db import models
from accounts.models import CustomUser
from phonenumber_field.modelfields import PhoneNumberField


class Table(models.Model):
    name = models.CharField(max_length=255)
    min_seats = models.IntegerField()
    max_seats = models.IntegerField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Reservation(models.Model):
    table = models.ForeignKey(Table, on_delete=models.RESTRICT)
    count = models.IntegerField()
    name = models.CharField(max_length=255)
    phone = PhoneNumberField(null=False, blank=False)
    email = models.EmailField(null=True, blank=True)
    time = models.TimeField()
    date = models.DateField()

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class ReservationContact(models.Model):
    type = models.CharField(max_length=25)
    content = models.TextField()

    def __str__(self):
        return self.type

reservation/forms.py
from django import forms
from .models import Reservation


class ReservationForm(forms.ModelForm):
    date = forms.DateField(input_formats=['%d/%m/%Y'])
    table = forms.IntegerField(required=False)

    class Meta:
        model = Reservation
        fields = '__all__'
        # exclude = ['table','status']

reservation/views.py
from django.shortcuts import render
from .models import Reservation, Table, ReservationContact
from .forms import ReservationForm
from django.contrib import messages
from django.core.mail import send_mail


def reservation_view(request):
    reservation_info = ReservationContact.objects.all()
    if request.method == 'POST':
        form = ReservationForm(request.POST)
        if form.is_valid():
            changed_form = form.save(commit=False)
            count = form.cleaned_data['count']
            date = form.cleaned_data['date']
            time = form.cleaned_data['time']
            reserved = Reservation.objects.filter(date=date, time=time)
            table = Table.objects.exclude(id__in=
                                          reserved.values_list('table_id', flat=True)).filter(min_seats__lte=count,
                                                                                              max_seats__gte=count).first()
            if table:
                changed_form.table = table
                changed_form.save()
                successful_message = 'Table "{}" is successfully reserved at "{}" on "{}" for you.'.format(table.name,
                                                                                                           time.strftime(
                                                                                                               '%H:%M'),
                                                                                                           date)
                messages.add_message(request, messages.SUCCESS, successful_message)

                send_mail(
                    "Restaurant Reservation", successful_message, "info@mahyarnazari.ir", [request.user.email],
                    fail_silently=False,)
            else:
                messages.add_message(request, messages.ERROR,
                                     'There are no empty tables at this time. Please choose another time.')

        else:
            if form.errors:
                for field in form:
                    for error in field.errors:
                        messages.add_message(request, messages.ERROR, error)

    context = {'reservation_info': reservation_info}
    return render(request, 'reservation/reservation.html', context=context)

templates/reservation/reservation.html
{% extends 'base.html' %}
{% load  background_tags %}
{% block content %}

    <!-- Title Page -->
    <section class="bg-title-page flex-c-m p-b-80 p-l-15 p-r-15"
             style="min-height: 100%; background-image: url({{ background|image_url:'reservation' }});">
        <h2 class="tit6 t-center">
            Reservation
        </h2>
    </section>

    <!-- Reservation -->
    <section class="section-reservation bg1-pattern p-t-100 p-b-113">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 p-b-30">
                    <div class="t-center">
						<span class="tit2 t-center">
							Reservation
						</span>

                        <h3 class="tit3 t-center m-b-35 m-t-2">
                            Book table
                        </h3>
                    </div>
                    {% if request.user.is_authenticated %}
                        <form class="wrap-form-reservation size22 m-l-r-auto" method="post"
                              action="{% url 'reservation:reservation' %}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-4">
                                    <!-- Name -->
                                    <span class="txt9">
									Name
								</span>

                                    <div class="wrap-inputname size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="name"
                                               value="{{ request.user.get_full_name }}" readonly>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Phone -->
                                    <span class="txt9">
									Phone
								</span>

                                    <div class="wrap-inputphone size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="tel" name="phone"
                                               value="{{ request.user.phone.as_international }}" readonly>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Email -->
                                    <span class="txt9">
									Email
								</span>

                                    <div class="wrap-inputemail size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="email"
                                               value="{{ request.user.email }}" readonly>
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <!-- Date -->
                                    <span class="txt9">
									Date
								</span>

                                    <div class="wrap-inputdate pos-relative txt10 size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="my-calendar bo-rad-10 sizefull txt10 p-l-20" type="text"
                                               name="date">
                                        <i class="btn-calendar fa fa-calendar ab-r-m hov-pointer m-r-18"
                                           aria-hidden="true"></i>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Time -->
                                    <span class="txt9">
									Time
								</span>

                                    <div class="wrap-inputtime size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <!-- Select2 -->
                                        <select class="selection-1" name="time">
                                            <option>8:00</option>
                                            <option>8:30</option>
                                            <option>9:00</option>
                                            <option>9:30</option>
                                            <option>10:00</option>
                                            <option>10:30</option>
                                            <option>12:00</option>
                                            <option>12:30</option>
                                            <option>13:00</option>
                                            <option>13:30</option>
                                            <option>14:00</option>
                                            <option>14:30</option>
                                            <option>15:00</option>
                                            <option>15:30</option>
                                            <option>19:00</option>
                                            <option>19:30</option>
                                            <option>20:00</option>
                                            <option>20:30</option>
                                            <option>21:00</option>
                                            <option>21:30</option>
                                            <option>22:00</option>
                                            <option>22:30</option>
                                            <option>23:00</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- People -->
                                    <span class="txt9">
									People
								</span>

                                    <div class="wrap-inputpeople size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <!-- Select2 -->
                                        <select class="selection-1" name="count">
                                            <option value="1">1 person</option>
                                            <option value="2">2 people</option>
                                            <option value="3">3 people</option>
                                            <option value="4">4 people</option>
                                            <option value="5">5 people</option>
                                            <option value="6">6 people</option>
                                            <option value="7">7 people</option>
                                            <option value="8">8 people</option>
                                            <option value="9">9 people</option>
                                            <option value="10">10 people</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="wrap-btn-booking flex-c-m m-t-6">

                                <!-- Button3 -->
                                <button type="submit" class="btn3 flex-c-m size13 txt11 trans-0-4">
                                    Book Table
                                </button>
                            </div>
                        </form>
                    {% else %}

                        <p><h2 class="txt36 t-center">* In order to make a reservation, you must sign in first. <a
                            href="{% url 'accounts:login' %}?next={{ request.path }}">Click Here!</a></h2>

                        <form class="py-5 wrap-form-reservation size22 m-l-r-auto">
                            <div class="row">
                                <div class="col-md-4">
                                    <!-- Name -->
                                    <span class="txt9">
									Name
								</span>

                                    <div class="wrap-inputname size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="hidden" name="name">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Phone -->
                                    <span class="txt9">
									Phone
								</span>

                                    <div class="wrap-inputphone size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="hidden" name="phone">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Email -->
                                    <span class="txt9">
									Email
								</span>

                                    <div class="wrap-inputemail size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="bo-rad-10 sizefull txt10 p-l-20" type="hidden" name="email">
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-md-4">
                                    <!-- Date -->
                                    <span class="txt9">
									Date
								</span>

                                    <div class="wrap-inputdate pos-relative txt10 size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <input class="my-calendar bo-rad-10 sizefull txt10 p-l-20" type="hidden"
                                               name="date">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- Time -->
                                    <span class="txt9">
									Time
								</span>

                                    <div class="wrap-inputtime size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <!-- Select2 -->
                                        <input class="my-calendar bo-rad-10 sizefull txt10 p-l-20" type="hidden"
                                               name="time">
                                    </div>
                                </div>

                                <div class="col-md-4">
                                    <!-- People -->
                                    <span class="txt9">
									People
								</span>

                                    <div class="wrap-inputpeople size12 bo2 bo-rad-10 m-t-3 m-b-23">
                                        <!-- Select2 -->
                                        <input class="my-calendar bo-rad-10 sizefull txt10 p-l-20" type="hidden"
                                               name="count">
                                    </div>
                                </div>
                            </div>

                        </form>

                    {% endif %}
                </div>
            </div>

            <div class="info-reservation flex-w p-t-80">
                {% for item in reservation_info %}
                    <div class="col-md-6 col-lg-6 col-sm-6 size23 w-full-md p-t-40 p-r-30 p-r-0-md">
                        <h4 class="txt5 m-b-18">
                            {{ item.type }}
                        </h4>

                        <p class="size25">
                            {{ item.content }}
                        </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}