blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'
urlpatterns = [
    path('', blog_view, name='index'),
    path('<int:pid>/', blog_single, name='single'),
    path('category/<str:cat_name>/', blog_view, name='category'),
    path('author/<str:author_username>/', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path('rss/feed/', LatestEntriesFeed()),
    path('archive/<str:month>/<int:year>/', blog_view, name='archive'),
]

main/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from main.views import *


app_name = 'website'
urlpatterns = [
    path('', index_view, name='index'),
    path('contact/', contact_view, name='contact'),
    path('about/', about_view, name='about'),
    path('newsletter/', newsletter_view, name='newsletter'),
    path('maintenance/', maintenance_view, name='maintenance'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from main.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
from menu.sitemaps import MenuSitemap
from reservation.sitemaps import ReservationSitemap
from restaurant.setting.dev import STATIC_ROOT, MEDIA_ROOT

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'menu': MenuSitemap,
    'reservation': ReservationSitemap
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('blog/', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('accounts.urls')),
    path('menu/', include('menu.urls')),
    path('reservation/', include('reservation.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=MEDIA_ROOT)

blog/models.py
from django.db import models
from accounts.models import CustomUser
from django.urls import reverse
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill  # or try ResizeToFill


class Category(models.Model):
    name = models.CharField(max_length=255)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    image = ProcessedImageField(upload_to='blog/', format='JPEG', processors=[ResizeToFill(1366, 768)],
                                options={'quality': 80}, default='default/no-image.jpg')
    image_thumbnail = ImageSpecField(source='image',
                                     processors=[ResizeToFill(160, 120)],
                                     format='JPEG',
                                     options={'quality': 70})
    author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category, )
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-published_date']

    def __str__(self):
        return self.title

    def increase_counted_views(self):
        self.counted_views += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog:single', kwargs={'pid': self.id})


class Comment(models.Model):
    name = models.CharField(max_length=255)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField()
    comment = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import Comment
from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'comment']

blog/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.contrib import messages
from calendar import month_name


# Create your views here.
def blog_view(request, **kwargs):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status=1).order_by('-published_date')
    if 'cat_name' in kwargs:
        posts = posts.filter(category__name=kwargs['cat_name'])
    if 'author_username' in kwargs:
        posts = posts.filter(author__username=kwargs['author_username'])
    if 'month' in kwargs:
        calender = {month: index for index, month in enumerate(month_name) if month}
        posts = posts.filter(published_date__month=calender[kwargs['month']], published_date__year=kwargs['year'])
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)


def blog_single(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 '{} ,your comment has been submitted successfully.'.format(request.POST['name']))
        else:
            messages.add_message(request, messages.ERROR, 'Your comment has not been submitted. Please try again.')
    post = get_object_or_404(Post, id=pid, status=1, published_date__lte=timezone.now())
    comments = Comment.objects.filter(post=post, approved=True)
    next_post = Post.objects.filter(published_date__gt=post.published_date, published_date__lte=timezone.now(),
                                    status=1).order_by('published_date').first()
    previous_post = Post.objects.filter(published_date__lt=post.published_date, published_date__lte=timezone.now(),
                                        status=1).order_by('published_date').last()
    post.increase_counted_views()
    form = CommentForm()
    context = {'post': post, 'next_post': next_post, 'previous_post': previous_post, 'comments': comments, 'form': form}
    return render(request, 'blog/blog-single.html', context)


def blog_search(request):
    posts = Post.objects.filter(published_date__lte=timezone.now(), status=1).order_by('-published_date')
    if request.method == 'GET':
        if q := request.GET.get('q'):
            posts = posts.filter(content__contains=q)
    context = {'posts': posts}
    return render(request, 'blog/blog-home.html', context)

templates/blog/blog-home.html
{% extends 'base.html' %}
{% load blog_tags %}
{% load background_tags %}
{% block content %}

    <!-- Title Page -->
    <section class="bg-title-page flex-c-m p-t-160 p-b-80 p-l-15 p-r-15"
             style="min-height: 250px; background-image: url({{ background|image_url:'blog_home' }});">
        <h2 class="tit6 t-center">
            Blog
        </h2>
    </section>

    <!-- Content page -->
    <section>
        <div class="bread-crumb bo5-b p-t-17 p-b-17">
            <div class="container">
                <a href="{% url 'website:index' %}" class="txt27">
                    Home
                </a>

                <span class="txt29 m-l-10 m-r-10">/</span>

                <span class="txt29">
					Blog
				</span>
            </div>
        </div>

        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-9">
                    <div class="p-t-80 p-b-124 bo5-r h-full p-r-50 p-r-0-md bo-none-md">
                        <!-- Block4 -->
                        {% for post in posts %}
                            <div class="blo4 p-b-63">
                                <div class="pic-blo4 hov-img-zoom bo-rad-10 pos-relative">
                                    <a href="{% url 'blog:single' pid=post.id %}">
                                        <img src="{{ post.image.url }}" alt="IMG-BLOG">
                                    </a>

                                    <div class="date-blo4 flex-col-c-m">
									<span class="txt30 m-b-4">
										{{ post.published_date|date:"d" }}
									</span>

                                        <span class="txt31">
										{{ post.published_date|date:"M, Y" }}
									</span>
                                    </div>
                                </div>

                                <div class="text-blo4 p-t-33">
                                    <h4 class="p-b-16">
                                        <a href="{% url 'blog:single' pid=post.id %}" class="tit9">{{ post.title }}</a>
                                    </h4>

                                    <div class="txt32 flex-w p-b-10">
                                        <ul class="lnr lnr-user">
                                            <a style="font-size:10px"
                                               href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.get_full_name }}</a>
                                            <span class="m-r-6 m-l-4"> | </span>
                                        </ul>
                                        <ul class="lnr lnr-calendar-full">
                                            {{ post.published_date|date:"d M, Y" }}
                                            <span class="m-r-6 m-l-4"> | </span>
                                        </ul>
                                        <ul class="lnr lnr-eye">
                                            {{ post.counted_views }} Views
                                            <span class="m-r-6 m-l-4"> | </span>
                                        </ul>
                                        <ul class="lnr lnr-pencil">
                                            {% comments_count post %} Comment(s)
                                        </ul>
                                    </div>
                                    <div class="txt32 flex-w p-b-24">
                                        <span class="lnr lnr-tag">
										{% for cat in post.category.all %}
                                            <a style="font-size:12px"
                                               href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>
                                            {% if not forloop.last %}
                                                <span class="m-r-6 m-l-4">|</span>
                                            {% endif %}
                                        {% endfor %}
									    </span>
                                    </div>

                                    <p>
                                        {{ post.content|striptags|safe|truncatewords:50 }}
                                    </p>

                                    <a href="{% url 'blog:single' pid=post.id %}" class="dis-block txt4 m-t-30">
                                        Continue Reading
                                        <i class="fa fa-long-arrow-right m-l-10" aria-hidden="true"></i>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                        <!-- Pagination -->
                        <div class="pagination blog-pagination justify-content-center d-flex">
                            {% if posts.has_previous %}
                                <a href="?page={{ posts.previous_page_number }}"
                                   class="item-pagination flex-c-m trans-0-4"><</a>
                            {% endif %}
                            {% for p in posts.paginator.page_range %}
                                {% if posts.number == p %}
                                    <a href="?page={{ p }}"
                                       class="item-pagination flex-c-m trans-0-4 active-pagination">{{ p }}</a>
                                {% else %}
                                    <a href="?page={{ p }}" class="item-pagination flex-c-m trans-0-4">{{ p }}</a>
                                {% endif %}
                            {% endfor %}
                            {% if posts.has_next %}
                                <a href="?page={{ posts.next_page_number }}" class="item-pagination flex-c-m trans-0-4">></a>
                            {% endif %}

                        </div>

                    </div>
                </div>

                <div class="col-md-4 col-lg-3">
                    <div class="sidebar2 p-t-80 p-b-80 p-l-20 p-l-0-md p-t-0-md">
                        <!-- Search -->
                        {% include 'blog/blog_search.html' %}

                        <!-- Categories -->
                        {% categories_count %}

                        <!-- Most Popular -->
                        {% popular_posts_blogpage %}

                        <!-- Archive -->
                        {% archives_blog %}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load background_tags %}
{% load blog_tags %}
{% load humanize %}
{% block content %}

    <!-- Title Page -->
    <section class="bg-title-page flex-c-m p-t-160 p-b-80 p-l-15 p-r-15"
             style="min-height: 250px; background-image: url({{ background|image_url:'blog_single' }});">
        <h2 class="tit6 t-center">
            Blog
        </h2>
    </section>


    <!-- Content page -->
    <section>
        <div class="bread-crumb bo5-b p-t-17 p-b-17">
            <div class="container">
                <a href="{% url 'website:index' %}" class="txt27">
                    Home
                </a>

                <span class="txt29 m-l-10 m-r-10">/</span>

                <a href="{% url 'blog:index' %}" class="txt27">
                    Blog
                </a>

                <span class="txt29 m-l-10 m-r-10">/</span>

                <span class="txt29">
					{{ post.title }}
				</span>
            </div>
        </div>

        <div class="container">
            <div class="row ">
                <div class="col-md-8 col-lg-9">
                    <div class="p-t-80 p-b-124 bo5-r p-r-50 h-full p-r-0-md bo-none-md">
                        <!-- Block4 -->
                        <div class="blo4 p-b-63">
                            <!-- - -->
                            <div class="pic-blo4 hov-img-zoom bo-rad-10 pos-relative">
                                <a href="{{ post.image.url }}">
                                    <img src="{{ post.image.url }}" alt="IMG-BLOG">
                                </a>

                                <div class="date-blo4 flex-col-c-m">
									<span class="txt30 m-b-4">
										{{ post.published_date|date:"d" }}
									</span>

                                    <span class="txt31">
										{{ post.published_date|date:"M, Y" }}
									</span>
                                </div>
                            </div>

                            <!-- - -->
                            <div class="text-blo4 p-t-33">
                                <h4 class="p-b-16 tit9">{{ post.title }}></h4>
                                <div class="txt32 flex-w p-b-10">
                                    <ul class="lnr lnr-user">
                                        <a style="font-size:10px"
                                           href="{% url 'blog:author' author_username=post.author.username %}">{{ post.author.get_full_name }}</a>
                                        <span class="m-r-6 m-l-4"> | </span>
                                    </ul>
                                    <ul class="lnr lnr-calendar-full">
                                        {{ post.published_date|date:"d M, Y" }}
                                        <span class="m-r-6 m-l-4"> | </span>
                                    </ul>
                                    <ul class="lnr lnr-eye">
                                        {{ post.counted_views }} Views
                                        <span class="m-r-6 m-l-4"> | </span>
                                    </ul>
                                    <ul class="lnr lnr-pencil">
                                        {% comments_count post %} Comment(s)
                                    </ul>
                                </div>
                                <div class="txt32 flex-w p-b-24">
                                        <span class="lnr lnr-tag">
										{% for cat in post.category.all %}
                                            <a style="font-size:12px"
                                               href="{% url 'blog:category' cat_name=cat.name %}">{{ cat.name }}</a>
                                            {% if not forloop.last %}
                                                <span class="m-r-6 m-l-4">|</span>
                                            {% endif %}
                                        {% endfor %}
									    </span>
                                </div>
                                <p>
                                    {{ post.content|safe }}
                                </p>
                            </div>
                        </div>

                        <div class="comments-area">
                            <h4>{{ comments|length }} Comment(s)</h4>
                            {% for comment in comments %}
                                <div class="comment-list">
                                    <div class="single-comment justify-content-between d-flex">
                                        <div class="user justify-content-between d-flex">
                                            <div class="thumb">
                                                <img src="{% static 'default/no-avatar.png' %}" alt="">
                                            </div>
                                            <div class="desc">
                                                <h5><a href="#">{{ comment.name }}</a></h5>
                                                <p class="date">{{ comment.created_date|naturaltime }}</p>
                                                <p class="comment">
                                                    {{ comment.comment }}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% empty %}
                                There are no comments yet
                            {% endfor %}
                        </div>

                        <!-- Leave a comment -->
                        <form class="comment-form p-t-10" method="POST" action="{% url 'blog:single' pid=post.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="post" value="{{ post.id }}">
                            <h4 class="txt33 p-b-14">
                                Leave a Comment
                            </h4>
                            {% if request.user.is_authenticated %}
                                <div class="size30 bo2 bo-rad-10 m-t-3 m-b-20">
                                    <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="name"
                                           value="{{ request.user.get_full_name }}" readonly>
                                </div>

                                <div class="size30 bo2 bo-rad-10 m-t-3 m-b-20">
                                    <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="email"
                                           value="{{ request.user.email }}" readonly>
                                </div>
                            {% else %}
                                <div class="size30 bo2 bo-rad-10 m-t-3 m-b-20">
                                    <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="name"
                                           placeholder="Name *">
                                </div>

                                <div class="size30 bo2 bo-rad-10 m-t-3 m-b-20">
                                    <input class="bo-rad-10 sizefull txt10 p-l-20" type="text" name="email"
                                           placeholder="Email *">
                                </div>
                            {% endif %}
                            <textarea class="bo-rad-10 size29 bo2 txt10 p-l-20 p-t-15 m-b-10 m-t-40" name="comment"
                                      placeholder="Comment..."></textarea>


                            <div class="m-t-3 m-b-20">{{ form.captcha }}</div>
                            <!-- Button3 -->
                            <button type="submit" class="btn3 flex-c-m size31 txt11 trans-0-4">
                                Post Comment
                            </button>
                        </form>
                    </div>
                </div>

                <div class="col-md-4 col-lg-3">
                    <div class="sidebar2 p-t-80 p-b-80 p-l-20 p-l-0-md p-t-0-md">
                        <!-- Search -->
                        {% include 'blog/blog_search.html' %}

                        <!-- Categories -->
                        {% categories_count %}

                        <!-- Most Popular -->
                        {% popular_posts_blogpage %}

                        <!-- Archive -->
                        {% archives_blog %}

                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/blog/blog_archive.html
{% load main_tags %}
<div class="archive">
    <h4 class="txt33 p-b-20 p-t-43">
        Archive
    </h4>

    <ul>
        {% for date, count in archives.items %}
            <li class="flex-sb-m p-t-8 p-b-8">
                <a href="{% url 'blog:archive' month=date|split:1 year=date|split:2 %}" class="txt27">
                    {{ date }}
                </a>
                <span class="txt29">
					({{ count }})
                </span>
            </li>
        {% endfor %}

    </ul>
</div>

templates/blog/blog_category.html
<div class="categories">
    <h4 class="txt33 bo5-b p-b-35 p-t-58">
        Categories
    </h4>

    <ul>
        {% for name, count in categories.items %}
            <li class="bo5-b p-t-8 p-b-8">
                <a href="{% url 'blog:category' cat_name=name %}" class="txt27 d-flex justify-content-between">
                    <p>{{ name }}</p>
                    <p>{{ count }}</p>
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

templates/blog/blog_popular.html
{% load humanize %}
<div class="popular">
    <h4 class="txt33 p-b-35 p-t-58">
        Most popular
    </h4>

    <ul>
        {% for post in posts %}
            <li class="flex-w m-b-25">
                <div class="size16 bo-rad-10 wrap-pic-w of-hidden m-r-18">
                    <a href="{% url 'blog:single' post.id %}">
                        <img src="{{ post.image_thumbnail.url }}" alt="IMG-BLOG">
                    </a>
                </div>

                <div class="size28">
                    <a href="{% url 'blog:single' post.id %}" class="dis-block txt28 m-b-8">
                        {{ post.title }}
                    </a>

                    <span class="txt14">
                        {{ post.published_date|naturaltime }}
                    </span>
                </div>
            </li>
        {% endfor %}

    </ul>
</div>

templates/blog/blog_search.html
<form action="{% url 'blog:search' %}" method="get">
<div class="search-sidebar2 size12 bo2 pos-relative">
    <input class="input-search-sidebar2 txt10 p-l-20 p-r-55" type="text" name="q"
           placeholder="Search">
    <button class="btn-search-sidebar2 flex-c-m ti-search trans-0-4"></button>

</div>
    </form>